import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import { ContactProvider } from "@/context/createContext";
import { Toaster } from "sonner";
import "./globals.css";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.className} antialiased`}>
        <ContactProvider>{children}</ContactProvider>
        <Toaster position="top-right" expand={false} richColors />
      </body>
    </html>
  );
}
