export const inputFields = [
  {
    id: "surname",
    label: "Patient Surname (*)",
    name: "surname",
    type: "text",
    required: true,
    placeholder: "Enter patient surname",
    className: "focus:border-blue-2 duration-200",
  },
  {
    id: "name",
    label: "Patient FirstName (*)",
    name: "name",
    type: "text",
    required: true,
    placeholder: "Enter first name",
    className: "focus:border-blue-2 duration-200",
  },
  {
    id: "age",
    label: "Age (*)",
    name: "age",
    type: "number",
    required: true,
    className: "focus:border-blue-2 duration-200",
  },
  {
    id: "doB",
    label: "Date of Birth",
    name: "doB",
    type: "date",
    placeholder: "",
  },
  {
    id: "bloodGroup",
    label: "Blood Group",
    name: "bloodGroup",
    type: "dropdown",
    // placeholder: "Select Blood Group",
    className: "focus:border-blue-2 duration-200",
    placeholder: ` A+, A-, B+, B-, AB+, AB-, O+, O-`,
  },
  {
    id: "gender",
    label: "Gender (*)",
    name: "gender",
    type: "text",
    placeholder: "Male/Female/Child",
    required: true,
    className: "focus:border-blue-2 duration-200",
  },
  {
    id: "address",
    label: "Current Address",
    name: "address",
    type: "text",
    placeholder: "Enter Patient Current Address ",
    className: "focus:border-blue-2 duration-200",
  },
  {
    id: "homeTown",
    label: "HomeTown ID",
    name: "homeTown",
    type: "text",
    placeholder: "Enter Patient HomeTown ",
    className: "focus:border-blue-2 duration-200",
  },
  {
    id: "contactNumber",
    label: "Mobile Number (*)",
    name: "contactNumber",
    type: "text",
    required: true,
    placeholder: "0812345678",
    className: "focus:border-blue-2 duration-200",
  },
  // {
  //   id: "height",
  //   label: "Height",
  //   name: "height",
  //   type: "text",
  // },
  // {
  //   id: "weight",
  //   label: "Weight",
  //   name: "weight",
  //   type: "text",
  // },
];
